In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Absolute Error

In [4]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error:",total_error)
    mae = total_error/len(y_predicted)
    print("MAE:",mae)
    return mae

In [5]:
 mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

# Implement same thing using numpy in much easier way

In [6]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [8]:
np.mean(np.abs(y_predicted-y_true))

0.5

# Implement Log Loss or Binary Cross Entropy


In [9]:
np.log([0])

/tmp/ipykernel_6278/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [11]:
np.log([0.0000000000000000000001])

array([-50.65687205])

In [13]:
elpison = 1e-15

In [15]:
y_predicted_new = [max(i,elpison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [16]:
y_predicted_new =[min(i,1-elpison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [17]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [19]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [25]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [26]:
log_loss(y_true, y_predicted)

17.2696280766844